banner:
  location: config/banner.txt
  encoding: utf-8
server:
  session:
    timeout: 2
  context-path: /
  session-timeout: 1800
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
  port: 8088
  uri-encoding: utf-8
security:
  basic:
    enabled: false
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#  profiles:
#    active: dev
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  mvc:
    favicon:
      enabled: false
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/robotcms?useUnicode=true&characterEncoding=utf8
#      数据库账号
      username: root
#      数据库密码
      password: lik
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
  session:
    store-type: HASH_MAP
#  devtools:
#    restart:
#      enabled: true
#  aop:
#    proxy-target-class: true

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  typeAliasesPackage: com.robotcms.**.domain
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    capital-mode: true

    #调试
#    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#logging
logging:
  level: info
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

custom:
  autoLogOutTime: 600000


ifast:
  project-name: robotcms
  project-root-u-r-l: http://localhost:8088/
  demoMode: false
  jwt:
    userPrimaryKey: userId
    expireTime: 300000

dream:
  weixin:
    dev-mode: true
    wx-configs:
      - appId: wx9803d1188fa5fbda
        appSecret: db859c968763c582794e7c3d003c3d87
      - appId: wxc03edcd008ad1e70
        appSecret: 11ed9e2b8e3e3c131e7be320a42b2b5a
        token: 123456
    wxa-config:
      appid: wx4f53594f9a6b3dcb
      appSecret: eec6482ba3804df05bd10895bace0579
shiro:
  globalSessionTimeout: 2000